# Generated by Django 6.0.1 on 2026-06-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParametresSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default='Rédaction Ensoleillé — La Presse', max_length=120)),
                ('slogan', models.CharField(default="Ensoleillé, lumière sur l'obscurité !", max_length=160)),
                ('description', models.TextField(blank=True, default="Lumière sur l'obscurité : l'information vérifiée du Bénin et de l'Afrique de l'Ouest.")),
                ('logo', models.ImageField(blank=True, upload_to='config/')),
                ('favicon', models.ImageField(blank=True, upload_to='config/')),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('facebook', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('google_analytics_id', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
