# Generated by Django 6.0.1 on 2026-06-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, help_text='ca-pub-XXXXXXXXXXXX', max_length=40)),
                ('actif', models.BooleanField(default=False)),
                ('slot_header', models.CharField(blank=True, max_length=20)),
                ('slot_in_article', models.CharField(blank=True, max_length=20)),
                ('slot_sidebar', models.CharField(blank=True, max_length=20)),
                ('auto_ads', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration AdSense',
                'verbose_name_plural': 'Configuration AdSense',
            },
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='pub/')),
                ('code_html', models.TextField(blank=True, help_text="Si bannière HTML/JS au lieu d'une image")),
                ('lien', models.URLField(blank=True)),
                ('emplacement', models.CharField(choices=[('header', 'Bannière header'), ('sidebar', 'Colonne latérale'), ('in_article', "Dans l'article"), ('footer', 'Pied de page'), ('popup', 'Pop-up / interstitiel'), ('between', 'Entre les articles (flux)')], max_length=20)),
                ('annonceur', models.CharField(blank=True, max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clics', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publicité',
                'ordering': ['emplacement', '-created_at'],
            },
        ),
    ]
