# Generated by Django 5.0.14 on 2026-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='emplacement',
            field=models.CharField(choices=[('header', 'Bannière header'), ('sidebar', 'Colonne latérale'), ('in_article', "Dans l'article"), ('footer', 'Pied de page'), ('popup', 'Pop-up / interstitiel'), ('between', 'Entre les articles (flux)'), ('hero_carre', 'Carré sous le hero (100×100)'), ('fin_colonne', 'Fin de colonne articles')], max_length=20),
        ),
    ]
