# Generated by Django 6.0.1 on 2026-06-21 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#F5A623', max_length=7)),
                ('icone_svg', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('en_menu', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('role', models.CharField(default='Rédacteur', max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='auteurs/')),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auteur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_couverture', models.ImageField(upload_to='couvertures/%Y/%m/')),
                ('credit_image', models.CharField(blank=True, max_length=160)),
                ('titre', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('chapeau', models.TextField(help_text="Le chapô : 1 à 3 phrases d'accroche")),
                ('contenu', models.TextField(help_text='Contenu riche : gras, italique, paragraphes, citations…')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=12)),
                ('a_la_une', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('epingle', models.BooleanField(default=False)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('temps_lecture', models.PositiveSmallIntegerField(default=0, help_text='minutes, auto-calculé')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_image', models.ImageField(blank=True, upload_to='og/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.categorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='articles.tag')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-date_publication'],
                'indexes': [models.Index(fields=['-date_publication', 'statut'], name='articles_ar_date_pu_9373a3_idx')],
            },
        ),
    ]
